# Generated by Django 4.0.5 on 2022-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knoxapp', '0002_alter_user_managers_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
