# Generated by Django 4.0.5 on 2022-06-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knoxapp', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCustom',
        ),
    ]
