# Generated by Django 4.0.5 on 2022-06-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knoxapp', '0004_rename_user_usercustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
