# Generated by Django 4.0.1 on 2022-05-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTp', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTp', models.CharField(max_length=50, verbose_name='Nombre Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('marca', models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto')),
            ],
        ),
    ]
