# Generated by Django 3.1.5 on 2022-06-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTp', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTp', models.CharField(max_length=50, verbose_name='Nombre Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idpro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('img', models.ImageField(null=True, upload_to='fotoproducto/')),
                ('marca', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto')),
            ],
        ),
    ]
