# Generated by Django 4.0.4 on 2022-05-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_img_alter_cliente_idcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
