# Generated by Django 4.0.4 on 2022-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='fotoproducto/'),
        ),
    ]
